### ISSUE TITLE
python 里最好用的aliddns

### ISSUE THREAD

**Issue by jgpgtg** [quancs/AliDDNS#1]
专门过来加一星🌟

**Comment by quancs** [comment]
谢谢，受宠若惊 哈哈~

**Comment by jgpgtg** [comment]
有一个问题，就是设置两条cron时，会出现只解析一条，另一条不会正常的修改，手动使用正常

**Comment by quancs** [comment]
多条cron应该是没有问题的。可能是有一条cron没有执行。我是这么设置的，正常使用
*/5 * * * * python3 /home/quancs/AliDDNS/aliddns.py ****** ************ pan baidu.com > /dev/null

*/5 * * * * python3 /home/quancs/AliDDNS/aliddns.py ****** ************ @ baidu.com > /dev/null

**Comment by jgpgtg** [comment]
回答这么快，不睡觉啊，检查了一遍，clone的文件夹是AliDDNS，我手添了一条AlIDDNS不怎么明显🙈
