### ISSUE TITLE
能否增加一个参数

### ISSUE THREAD

**Issue by jgpgtg** [quancs/AliDDNS#2]
情景
我现在是在树莓派ubuntu server上安装aliddns，但是主路由无法安装python,可否增加一个后缀参数，比如上级路由是::1，直接填入后缀即可，对局域网其他主机也适用，你看可行吗

**Comment by quancs** [comment]
按照你的叙述，不在主路由器上面运行，在与主路由同一局域网下面的其他任一一台电脑上运行脚本都是可以的，不一定非要主路由

**Comment by quancs** [comment]
最后的效果都是相同的——将整个局域网的互联网IP绑定到域名上面

**Comment by jgpgtg** [comment]
有设备非主机，也不能运行python 只开放个别端口，比如nas，以及嵌入设备，但后缀是固定的，设想有两种方式，1.在运营脚本的机器上nslookup本地设备名称获取全局域网设备地址，再由脚本选择对应RR进行更新，2,增加后缀参数，在运行脚本的机器实现

**Comment by quancs** [comment]
不明白你在说什么，根据猜想，你说的不属于DDNS。此外，我认为此软件在阿里云解析方面已经工作良好，无意在其中增加其他不相关功能。你若有其他需求可以自己写软件实现，然后配合本脚本实现你的特殊需求。

**Comment by jgpgtg** [comment]
好的，明白，我自己修改一下吧
